"""empty message

Revision ID: 4df28185915d
Revises: f440ba98f690
Create Date: 2025-12-16 18:39:46.224295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df28185915d'
down_revision: Union[str, Sequence[str], None] = 'f440ba98f690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('orders')
    op.drop_table('products')
    # ### end Alembic commands ###
